##Version : v2.0.2
- name: Deploy k8s cluster on linux nodes
  hosts: all

  roles:
    - name: Fetch latest version of software components to be installed from GitHub API
      role: fetch_latest_version_number 
      when: ('local-ansible-control-host' in inventory_hostname)

    - name:  
      role: prepare_all_the_cluster_nodes 
      when: ( 'k8s_cluster_ctrl_plane_node' in group_names) and  ( 'k8s_cluster_worker_nodes' in group_names)

        #    - role: install_and_configure_the_cluster
        #      when: ( 'k8s_cluster_ctrl_plane_node' in group_names)

        #    - role: join_worker_nodes_to_the_cluster
        #      when: ( 'k8s_cluster_worker_nodes' in group_names)

        #    - role: check_cluster_ready_status
        #      when: ( 'k8s_cluster_ctrl_plane_node' in group_names)

########################### EOF ##########################################
