##Version : v2.0.2
- name: Deploy k8s cluster on linux nodes
  hosts: k8s_cluster_ctrl_plane_node, k8s_cluster_worker_nodes
  vars_files: vars.yaml
  roles:
    - name: Fetch latest version of software components to be installed from GitHub API
      role: fetch_latest_version_number 
      delegate_to: localhost

    - name: Prepare all the nodes for k8s cluster installation   
      role: prepare_all_the_cluster_nodes 
    
    - name: Install and configure k8s cluster on control plane node using kubeadm    
      role: install_and_configure_the_cluster
      when: ( 'k8s_cluster_ctrl_plane_node' in group_names)

        #    - role: join_worker_nodes_to_the_cluster
        #      when: ( 'k8s_cluster_worker_nodes' in group_names)

        #    - role: check_cluster_ready_status
        #      when: ( 'k8s_cluster_ctrl_plane_node' in group_names)

########################### EOF ##########################################
