#!/usr/bin/env ansible-playbook
- name: Install and configure the kubernetes cluster on linux nodes
  hosts: k8s_cluster_ctrl_plane_node, k8s_cluster_worker_nodes
  roles:
    - name: Fetch if version cache file exists in control plan node
      role: version_cache_check_in_control_plane
      when: ( 'k8s_cluster_ctrl_plane_node' in group_names)

    - name: Fetch latest version of software components to be installed from GitHub API
      role: fetch_latest_version_number 
      when: not (version_cache_loaded | default(false))

    - name: Prepare all the nodes for k8s cluster installation   
      role: prepare_all_the_cluster_nodes 

    - name: Apply firewalld rules if it is running
      role: apply_rules_for_firewalld
    
    - name: Install and configure k8s cluster on control plane node using kubeadm    
      role: install_and_configure_the_cluster
      when: ( 'k8s_cluster_ctrl_plane_node' in group_names)

    - name: Join worker nodes with the k8s cluster
      role: join_worker_nodes_to_the_cluster
      when: ( 'k8s_cluster_worker_nodes' in group_names)

    - name: Check k8s cluster Ready status
      role: check_cluster_ready_status
      when: ( 'k8s_cluster_ctrl_plane_node' in group_names)

########################### EOF ##########################################
