##Version : v2.0.0
### Optional CSI SMB Driver for k8s cluster
### Run it if required only after the k8s cluster is Ready
- name: Install CSI SMB Driver for k8s cluster 
  hosts: k8s_cluster_ctrl_plane_node
  become: false
  tasks:
    - name: Get latest version information of k8s csi-smb-driver from github API
      uri:
        url: https://api.github.com/repos/kubernetes-csi/csi-driver-smb/releases/latest
        return_content: true
      register: var_csi_driver_smb_release

    - set_fact:
        var_csi_driver_smb_latest_version: "{{ var_csi_driver_smb_release.json.tag_name }}"

    - debug:
        msg: |-
          Latest stable version to be installed of k8s csi-driver-smb is {{ var_csi_driver_smb_latest_version }}

    - name: Install CSI SMB drivers by remote from GitHub using kubectl
      shell: curl -skSL https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/{{ var_csi_driver_smb_latest_version }}/deploy/install-driver.sh | bash -s {{ var_csi_driver_smb_latest_version }} --
      register: var_csi_driver_smb_install_logs

    - debug:
        msg: |-
          {{ var_csi_driver_smb_install_logs.stdout_lines }}

    - name: completed, the csi-smb-driver pods are being deployed
      shell: kubectl get pods -A | grep -i csi-smb
      register: var_csi_driver_smb_pods_logs

    - debug:
        msg: |-
          {{ var_csi_driver_smb_pods_logs.stdout_lines }}
