##Version : v2.1.0
### Optional CSI NFS Driver for k8s cluster
### Run it if required only after the k8s cluster is Ready
- name: Install CSI NFS Driver for k8s cluster 
  hosts: k8s_cluster_ctrl_plane_node
  roles:
      role: install-k8s-csi-nfs-driver 

######################### EOF #############################
