#!/usr/bin/env ansible-playbook
##Version : v2.2.6
### Optional CSI NFS Driver for k8s cluster
### Run it if required only after the k8s cluster is Ready
- name: Install CSI NFS Driver for k8s cluster 
  hosts: k8s_cluster_ctrl_plane_node
  roles:
    - role: install_k8s_csi_nfs_driver 

######################### EOF #############################
