#!/usr/bin/env ansible-playbook
### Optional metallb installation for k8s cluster
### Run it if required only after the k8s cluster is Ready

- name: Install and configure MetalLB for k8s cluster 
  hosts: k8s_cluster_ctrl_plane_node
  gather_facts: false
  vars:
    k8s_metallb_ip_pool_range: "10.10.20.201-10.10.20.255" # Change it as per your environment
  roles:
    - role: install_and_configure_metallb 

######################### EOF #############################
