##Version : v2.0.1
### Role to Fetch latest version of software components to be installed from GitHub API
- name: Get latest version information of containerd
  uri:
    url: https://api.github.com/repos/containerd/containerd/releases/latest
    return_content: true
  register: var_containerd_release

- set_fact:
    var_containerd_latest_version: "{{ var_containerd_release.json.tag_name }}"

- debug:
    msg: |-
      Latest stable version to be installed of containerd is {{ var_containerd_latest_version }}

    
- name: Get latest version information of runc
  uri:
    url: https://api.github.com/repos/opencontainers/runc/releases/latest
    return_content: true
  register: var_runc_release

- set_fact:
    var_runc_latest_version: "{{ var_runc_release.json.tag_name }}"

- debug:
    msg: |-
      Latest stable version to be installed of runc is {{ var_runc_latest_version }}

- name: Get latest version information of kubernetes
  uri:
    url: https://api.github.com/repos/kubernetes/kubernetes/releases/latest
    return_content: true
  register: var_k8s_release

- set_fact:
    var_k8s_latest_version: "{{ var_k8s_release.json.tag_name }}"

- set_fact:
    var_k8s_version_major_minor: "{{ var_k8s_latest_version | regex_replace('.[0-9]+$', '') }}"

- debug:
    msg: |-
      Latest stable version to be installed of kubernetes is {{ var_k8s_latest_version }}
    
################################## EOF ###############################
