- name: Ensure gnupg is installed ( Debian based systems )
  become: true
  ansible.builtin.apt:
    name: gnupg
    state: present
    update_cache: true

- name: Ensure /etc/apt/keyrings directory exists ( Debian based systems )
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download k8s apt repository gpg key ( Debian based systems )
  become: true
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/{{ k8s_version_major_minor }}/deb/Release.key
    dest: /tmp/k8s-apt-key-{{ k8s_version_major_minor }}.asc
    mode: '0644'

- name: Dearmor and install k8s gpg key to apt keyrings ( Debian based systems )
  become: true
  ansible.builtin.command:
    cmd: >-
      gpg --batch --yes --dearmor
      -o /etc/apt/keyrings/k8s-apt-keyring-{{ k8s_version_major_minor }}.gpg
      /tmp/k8s-apt-key-{{ k8s_version_major_minor }}.asc
  args:
    creates: /etc/apt/keyrings/k8s-apt-keyring-{{ k8s_version_major_minor }}.gpg

- name: Add k8s deb repository ( Debian based systems )
  become: true
  apt_repository:
    filename: k8s-{{ k8s_version_major_minor }}
    repo: deb [signed-by=/etc/apt/keyrings/k8s-apt-keyring-{{ k8s_version_major_minor }}.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8s_version_major_minor }}/deb/ /
    state: present
    update-cache: true

- name: Get list of kubernetes versions with apt-cache ( Debian based systems )
  become: true
  command: apt-cache madison kubectl
  register: kubectl_versions
  changed_when: false

- name: Extract exact version string of kubernetes versions ( Debian based systems )
  set_fact:
    k8s_package_version: "{{ item.split('|')[1] | trim }}"
  loop: "{{ kubectl_versions.stdout_lines }}"
  when: item.split('|')[1] | trim is match('^' + (k8s_version | regex_replace('^v', '')) + '-')
  loop_control:
    label: "{{ item }}"

- name: Install kubelet, kubeadm and kubectl packages ( Debian based systems )
  become: true
  apt:
    name:
      - "kubelet={{ k8s_package_version }}"
      - "kubeadm={{ k8s_package_version }}"
      - "kubectl={{ k8s_package_version }}"
      - cri-tools
      - bash-completion 
    state: present

- name: Lock kubelet, kubeadm and kubectl packages from upgrades ( Debian based systems )
  become: true
  dpkg_selections:
    name: "{{ item }}"
    selection: "hold"
  loop:
    - kubelet
    - kubeadm
    - kubectl

######################################### EOF ############################################# 
