##Version : v2.2.4
- name: Add k8s gpg apt-key ( Debian based systems )
  become: true
  apt_key:
    keyring: /etc/apt/keyrings/k8s-apt-keyring-{{ var_k8s_version_major_minor }}.gpg
    url: https://pkgs.k8s.io/core:/stable:/{{ var_k8s_version_major_minor }}/deb/Release.key
    state: present

- name: Add k8s deb repository ( Debian based systems )
  become: true
  apt_repository:
    filename: k8s-{{ var_k8s_version_major_minor }}
    repo: deb [signed-by=/etc/apt/keyrings/k8s-apt-keyring-{{ var_k8s_version_major_minor }}.gpg] https://pkgs.k8s.io/core:/stable:/{{ var_k8s_version_major_minor }}/deb/ /
    state: present
    update-cache: true

- name: Install kubelet, kubeadm and kubectl packages ( Debian based systems )
  become: true
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl 
      - bash-completion 
    state: present

- name: Check whether kubelet, kubeadm and kubectl packages are locked ( Debian based systems )
  become: true
  shell: |
    if apt-mark showhold | grep -i -E '(kubeadm|kubectl|kubelet)'
    then
      exit 0
    else
      exit 1
    fi
  register: var_k8s_packages_debian_lock_status
  failed_when: false
  changed_when: false
  ignore_errors: true

- name: Lock kubelet, kubeadm and kubectl packages from upgrades ( Debian based systems )
  become: true
  command: apt-mark hold kubelet kubeadm kubectl
  when: var_k8s_packages_debian_lock_status.rc == 1

######################################### EOF ############################################# 
