##Version : v2.2.6
- name: Download latest official runc ( {{ var_runc_latest_version }}  ) binary to local-ansible-control-host
  delegate_to: local-ansible-control-host
  run_once: true
  get_url:
    url: "https://github.com/opencontainers/runc/releases/download/{{ var_runc_latest_version }}/runc.amd64"
    dest: "{{ var_runc_temp_binary }}"
    mode: 0755

- name: Copy downloaded runc binary from local-ansible-control-host to /usr/local/bin/runc of cluster node
  become: true
  copy:
    src: "{{ var_runc_temp_binary }}"
    dest: /usr/local/bin/runc
    owner: root
    group: root
    mode: 755
     
- name: Clean up {{ var_runc_temp_binary }} from local-ansible-control-host
  delegate_to: local-ansible-control-host
  run_once: true
  file:
    path: "{{ var_runc_temp_binary }}"
    state: absent

########################################### EOF ############################################
