##Version : v2.2.6
- name: Load the required kernel parameters
  become: true
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { key: 'net.ipv4.ip_forward', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }

- name: Create /etc/sysctl.d/k8s.conf for above loaded kernel parameters to be persistent
  become: true
  blockinfile:
    create: true
    path: /etc/sysctl.d/k8s.conf
    block: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    state: present

##################################### EOF #######################################
