##Version : v2.1.6
###Tasks to upgrade the system packages
- name: Include tasks to upgrade the system packages
  include_tasks: upgrade_os.yaml 


###Tasks to disable swap memory
- name: Include tasks to disable swap
  include_tasks: disable_swap.yaml 


###Tasks to load required kernel modules
- name: Include tasks to load required kernel modules
  include_tasks: load_kernel_modules.yaml


###Tasks to load required kernel parameters
- name: Include tasks to load required kernel parameters
  include_tasks: load_kernel_parameters.yaml


###Tasks to install runc
- name: Check if runc is already installed
  shell: command -v runc
  register: var_runc_check
  ignore_errors: true
  failed_when: false

- name: Notify if runc is already installed
  debug:
    msg: |-
      runc is already installed.
  when: var_runc_check.rc == 0

- name: Notify if runc is not installed
  debug:
    msg: |-
      runc is not installed. Proceeding with installation.
  when: var_runc_check.rc != 0

- name: Include tasks to download and install runc
  include_tasks: install_runc.yaml
  when: var_runc_check.rc != 0

- name: Check runc version
  command: runc --version
  register: var_check_runc_version

- name: Notify runc version
  debug:
    msg: |-
      {{ var_check_runc_version.stdout_lines }}


###Task to install containered
- name: Check if containerd is already installed
  shell: command -v containerd
  register: var_containerd_check
  ignore_errors: true
  failed_when: false  

- name: Notify if containerd is already installed
  debug:
    msg: |-
      Containerd is already installed.
  when: var_containerd_check.rc == 0

- name: Notify if containerd is not installed
  debug:
    msg: |-
      Containerd is not installed. Proceeding with installation.
  when: var_containerd_check.rc != 0

- name: Include tasks to download and install containerd
  include_tasks: install_containerd.yaml
  when: var_containerd_check.rc != 0

- name: Check containerd version
  command: containerd --version
  register: var_check_containerd_version

- name: Notify containerd version
  debug:
    msg: |-
      containerd version is {{ var_check_containerd_version.stdout_lines }}

- name: Restart containerd service to ensure it is running properly
  become: yes 
  systemd:
    name: containerd
    state: restarted

- name: Check containerd service status after the restart
  become: yes 
  systemd:
    name: containerd
    state: started
  register: var_containerd_service_status_after_restart

- name: Notify containerd service status after the restart
  debug:
    msg: containerd service status after restart is {{ var_containerd_service_status_after_restart.status.ActiveState }}
  when: var_containerd_service_status_after_restart is defined

        
###Task to install kubelet, kubeadm and kubectl packages 
- name: Tasks for RedHat based Distributions to install kubelet, kubeadm and kubectl packages
  when: ansible_os_family == "RedHat"
  include_tasks: redhat_tasks.yaml
    
- name: Tasks for Debian based Distributions to install kubelet, kubeadm and kubectl packages
  when: ansible_os_family == "Debian"
  include_tasks: debian_tasks.yaml

- name: Tasks for Suse based Distributions to install kubelet, kubeadm and kubectl packages
  when: ansible_os_family == "Suse"
  include_tasks: suse_tasks.yaml


###Tasks to Enable and start kubelet service                 
- name: Enable and start kubelet.service
  become: true
  systemd:
    name: kubelet.service
    enabled: yes
    state: started

- name: Check kubelet service status
  command: systemctl is-enabled kubelet
  register: kubelet_service_status

- name: Notify if the kubelet service is enabled
  debug:
    msg: |-
      kubelet service is enabled.
  when: kubelet_service_status.stdout == 'enabled'

################################# EOF ########################################
