##Version : v2.1.5
- name: Upgrade system packages of all the cluster nodes
  become: true
  block:
    - name: Upgrade the system packages ( RedHat based systems )
      when: ansible_os_family == "RedHat"
      dnf:
        update_cache: true
        name: "*"
        state: latest
      register: var_upgrade_status

    - name: Upgrade the system packages ( Debian based systems )
      when: ansible_os_family == "Debian"
      apt:
        update_cache: true
        upgrade: full
      register: var_upgrade_status
  
    - name: Upgrade the system packages ( Suse based systems )
      when: ansible_os_family == "Suse"
      zypper:
        update_cache: true
        name: "*"
        state: latest
      register: var_upgrade_status


- name: Reboot the systems that are upgraded and wait for them to come back online
  become: true
  reboot:
    msg: Reboot initiated by Ansible Control Host
    connect_timeout: 10
    post_reboot_delay: 60
    reboot_command: reboot
    reboot_timeout: 600
    test_command: whoami && systemctl is-active multi-user.target
  when: var_upgrade_status.changed


- name: Disable swap memory
  become: true
  block:
    - name: Turn off swap if active
      command: swapoff -a

    - name: Remove swap entry from fstab
      lineinfile:
        backup: true
        dest: /etc/fstab
        regexp: '^.* swap .*$'
        state: absent


###Task to Load required kernel modules and kernel parameters
- name: Load required kernel modules and kernel parameters
  become: true
  block:
    - name: Load overlay kernel module
      modprobe:
        name: overlay
        state: present

    - name: Load br_netfilter kernel module
      modprobe:
        name: br_netfilter
        state: present

    - name: Create /etc/modules-load.d/k8s.conf for the above loaded modules to be persistent
      blockinfile:
        create: true
        path: /etc/modules-load.d/k8s.conf
        block: |
          overlay
          br_netfilter
        state: present

    - name: Create /etc/sysctl.d/k8s.conf and update required kernel parameters to be persistent
      blockinfile:
        create: true
        path: /etc/sysctl.d/k8s.conf
        block: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
        state: present

    - name: Re-load the system kernel parameters
      command: sysctl --system


###Task to Install and configure latest version of containered using official binaries
- name: Install and configure latest version of containered using official binaries
  become: true
  block:
    - name: Download binary tarball of latest containerd ( {{ var_containerd_latest_version  }} ) to local-ansible-control-host
      delegate_to: local-ansible-control-host
      run_once: true
      get_url:
        url: https://github.com/containerd/containerd/releases/download/{{ var_containerd_latest_version }}/containerd-{{ var_containerd_latest_version | regex_replace('v', '') }}-linux-amd64.tar.gz
        dest: "{{ var_containerd_temp_binary_tarball }}"

    - name: Copy downloaded containerd binary tarball from local-ansible-control-host to cluster nodes
      copy:
        src: "{{ var_containerd_temp_binary_tarball }}"
        dest: "{{ var_containerd_temp_binary_tarball }}"
        mode: 755

    - name: Extract containerd bin under /usr/local
      unarchive:
        remote_src: true
        src: "{{ var_containerd_temp_binary_tarball }}"
        dest: /usr/local 

    - name: Create containerd configuration directory /etc/containerd
      file:
        path: /etc/containerd
        state: directory
        mode: 0755

    - name: Create /etc/containerd/config.toml
      file:
        path: /etc/containerd/config.toml
        state: touch

    - name: Generate containerd config and write it to /etc/containerd/config.toml
      become: false
      shell: containerd config default | sudo tee /etc/containerd/config.toml

    - name: Set SystemdCgroup as true in /etc/containerd/config.toml
      replace:  
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Verify SystemdCgroup setting
      command: grep 'SystemdCgroup' /etc/containerd/config.toml
      register: var_SystemdCgroup_output

    - debug:
        msg: |-
          {{ var_SystemdCgroup_output.stdout_lines }}

    - name: Download containerd.service file from GitHub
      get_url:
        url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
        dest: /etc/systemd/system/containerd.service

    - name: Reload systemd daemon
      systemd:
        name: daemon-reload

    - name: Enable and start containerd.service
      systemd:
        name: containerd.service
        enabled: yes
        state: started

    - name: Verify status of containerd service
      command: systemctl is-active containerd
      register: containerd_service_info

    - debug:
        msg: |-
          containerd service is {{ containerd_service_info.stdout_lines }}

    - name: Verify containerd version
      become: false
      command: containerd --version
      register: containerd_info

    - debug:
        msg: |-
          containerd version is {{ containerd_info.stdout_lines }}

    - name: Clean up {{ var_containerd_temp_binary_tarball }} from local-ansible-control-host
      delegate_to: local-ansible-control-host
      run_once: true
      file:
        path: "{{ var_containerd_temp_binary_tarball }}"
        state: absent

    - name: Clean up {{ var_containerd_temp_binary_tarball }} from all nodes
      file:
        path: "{{ var_containerd_temp_binary_tarball }}"
        state: absent


###Task to Install latest version of runc using official binaries
- name: Install latest version of runc using official binaries
  become: true
  block:
    - name: Download latest runc ( {{ var_runc_latest_version }}  ) binary to local-ansible-control-host
      delegate_to: local-ansible-control-host
      run_once: true
      get_url:
        url: "https://github.com/opencontainers/runc/releases/download/{{ var_runc_latest_version }}/runc.amd64"
        dest: "{{ var_runc_temp_binary }}"
        mode: 0755

    - name: Copy downloaded runc binary from local-ansible-control-host to /usr/local/bin/runc of cluster node
      copy:
        src: "{{ var_runc_temp_binary }}"
        dest: /usr/local/bin/runc
        mode: 755

    - name: Verify runc version
      become: false
      command: runc --version
      register: runc_info

    - debug:
        msg: |-
          {{ runc_info.stdout_lines }}

    - name: Clean up {{ var_runc_temp_binary }} from local-ansible-control-host
      delegate_to: local-ansible-control-host
      run_once: true
      file:
        path: "{{ var_runc_temp_binary }}"
        state: absent

        
###Task to Configure k8s repository to install kubelet, kubeadm and kubectl packages 
- name: Tasks for RedHat based Distributions
  when: ansible_os_family == "RedHat"
  include_tasks: redhat_tasks.yaml
    
- name: Tasks for Debian based Distributions
  when: ansible_os_family == "Debian"
  include_tasks: debian_tasks.yaml

- name: Tasks for Suse based Distributions
  when: ansible_os_family == "Suse"
  include_tasks: suse_tasks.yaml


###Task to Enable and start kubelet service                 
- name: Enable and start kubelet service
  become: true
  block:
    - name: Enable and start kubelet.service
      systemd:
        name: kubelet.service
        enabled: yes
        state: started

    - name: Check kubelet service status
      command: systemctl is-enabled kubelet
      register: kubelet_service_info

    - debug:
        msg: |-
          kubelet service is {{ kubelet_service_info.stdout_lines }}

################################# EOF ########################################
