##Version : v2.2.4
- name: Add k8s rpm repository ( Suse based systems )
  become: true
  zypper_repository:
    description: k8s-{{ var_k8s_version_major_minor }}
    name: k8s-{{ var_k8s_version_major_minor }}
    repo: https://pkgs.k8s.io/core:/stable:/{{ var_k8s_version_major_minor }}/rpm/
    auto_import_keys: true
    enabled: true
    state: present
    
- name: Install kubelet, kubeadm and kubectl packages ( Suse based systems )
  become: true
  zypper:
    update_cache: true
    name:
      - kubelet
      - kubeadm
      - kubectl 
      - bash-completion 
    state: present

- name: Check whether kubelet, kubeadm and kubectl packages are locked ( Suse based systems )
  become: true
  shell: |
    if zypper locks | grep -i -E '(kubeadm|kubectl|kubelet)'
    then
      exit 0
    else
      exit 1
    fi
  register: var_k8s_packages_suse_lock_status
  failed_when: false
  changed_when: false
  ignore_errors: true

- name: Lock kubelet, kubeadm and kubectl packages from upgrades ( Suse based systems )
  become: true
  command: zypper addlock kubelet kubeadm kubectl
  when: var_k8s_packages_suse_lock_status.rc == 1

################################## EOF ####################################
