##Version : v2.2.6
- name: Add k8s rpm repository ( Suse based systems )
  become: true
  zypper_repository:
    description: k8s-{{ var_k8s_version_major_minor }}
    name: k8s-{{ var_k8s_version_major_minor }}
    repo: https://pkgs.k8s.io/core:/stable:/{{ var_k8s_version_major_minor }}/rpm/
    auto_import_keys: true
    enabled: true
    state: present
    
- name: Install kubelet, kubeadm and kubectl packages ( Suse based systems )
  become: true
  zypper:
    update_cache: true
    name:
      - kubelet
      - kubeadm
      - kubectl 
      - bash-completion 
    state: present

- name: Ensure /etc/zypp/locks file exists ( Suse based systems )
  become: true
  file:
    path: /etc/zypp/locks
    state: touch
    mode: '0644'
    owner: root
    group: root

- name: Lock kubelet, kubeadm and kubectl packages from upgrades ( Suse based systems )
  become: true
  blockinfile:
    path: /etc/zypp/locks
    block: |

      type: package
      match_type: glob
      case_sensitive: on
      solvable_name: {{ item }}

    insertafter: EOF
    marker: ""
  loop:
    - kubelet
    - kubeadm
    - kubectl

################################## EOF ####################################
