### Optional csi-nfs-driver for k8s cluster
- name: Check if csi-nfs-driver pods already exist
  command: kubectl get pods -n kube-system --no-headers -l "app in (csi-nfs-node, csi-nfs-controller)" 
  register: csi_nfs_driver_pods_status
  failed_when: false
  changed_when: false
  ignore_errors: true

- set_fact:
    csi_nfs_install_status: "{{ 'already_installed' if (csi_nfs_driver_pods_status.stdout_lines | select('search', 'csi-nfs') | list | length > 0) else 'not_yet_installed' }}"

- name: Notify if csi-nfs-driver is already installed
  debug:
    msg: |-
      csi-nfs-driver is already installed.
  when: csi_nfs_install_status == 'already_installed'

- name: Get latest version information of csi-nfs-driver from GitHub API
  delegate_to: local-ansible-control-host
  run_once: true
  uri:
    url: "https://api.github.com/repos/kubernetes-csi/csi-driver-nfs/releases/latest"
    return_content: true
  register: csi_driver_nfs_release
  changed_when: false
  when: csi_nfs_install_status == 'not_yet_installed'

- set_fact:
    csi_driver_nfs_latest_version: "{{ csi_driver_nfs_release.json.tag_name }}"
  when: csi_nfs_install_status == 'not_yet_installed'

- name: Notify the version to be installed of k8s csi-driver-nfs
  debug:
    msg: |-
      Latest stable version to be installed of k8s csi-driver-nfs is {{ csi_driver_nfs_latest_version }}
  delegate_to: local-ansible-control-host
  run_once: true
  when: csi_nfs_install_status == 'not_yet_installed'

- name: Download the install-driver.sh script for csi-driver-nfs from GitHub
  get_url:
    url: "https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/{{ csi_driver_nfs_latest_version }}/deploy/install-driver.sh"
    dest: "/tmp/install-csi-driver-nfs.sh"
    mode: '0755'
  when: csi_nfs_install_status == 'not_yet_installed'

- name: Install csi-nfs-driver
  command: /tmp/install-csi-driver-nfs.sh {{ csi_driver_nfs_latest_version }}
  register: csi_driver_nfs_install_logs
  when: csi_nfs_install_status == 'not_yet_installed'

- name: Notify the results from csi-nfs-driver installation
  debug:
    msg: |-
      {{ csi_driver_nfs_install_logs.stdout_lines }}
  when: csi_nfs_install_status == 'not_yet_installed'

- name: Gather current status of pods from all namespaces
  command: kubectl get pods -A --no-headers
  register: list_of_all_pods
  failed_when: false
  changed_when: false
  ignore_errors: true
  when: csi_nfs_install_status == 'not_yet_installed'

- name: Get the status csi-nfs-driver pods being deployed
  set_fact:
    csi_driver_nfs_pods_logs: "{{ list_of_all_pods.stdout_lines | select('search', 'csi-nfs') | list }}"
  when: csi_nfs_install_status == 'not_yet_installed'

- name: Notify creation of csi-nfs-driver pods
  debug:
    msg: |-
      {{ csi_driver_nfs_pods_logs }}
  when: csi_nfs_install_status == 'not_yet_installed'

- name: Waiting for all the csi-nfs-driver pods to be Ready
  command: kubectl get pods -n kube-system --no-headers -l "app in (csi-nfs-node, csi-nfs-controller)"
  register: csi_nfs_driver_pods_status
  until: csi_nfs_driver_pods_status.stdout_lines | select('search', '^(\\S+)\\s+(\\d+)/(\\2)\\s+Running') | list | length == csi_nfs_driver_pods_status.stdout_lines | length
  retries: 500
  delay: 5
  changed_when: false
  failed_when: false
  when: csi_nfs_install_status == 'not_yet_installed'

- name: Get the current status of csi-nfs-driver pods
  command: kubectl get pods -n kube-system --no-headers -l "app in (csi-nfs-node, csi-nfs-controller)"
  register: csi_nfs_driver_pods_status
  changed_when: false
  failed_when: false

- name: Status of csi-nfs-driver pods if already installed
  debug:
    msg: |-
      {{ csi_nfs_driver_pods_status.stdout_lines }}
  when: csi_nfs_install_status == 'already_installed'

- name: Successfully deployed csi-nfs-driver pods for k8s cluster
  debug:
    msg: |-
      {{ csi_nfs_driver_pods_status.stdout_lines }}
  when: csi_nfs_install_status == 'not_yet_installed'

######################################## EOF #########################################
