- name: Gather the list of pods from all namespaces
  command: kubectl get pods -A --no-headers 
  register: list_of_all_pods
  failed_when: false
  changed_when: false
  ignore_errors: true

- name: Check if Calico CNI manifest has been applied already
  set_fact:
    calico_cni_manifest: "{{ 'applied_already' if (list_of_all_pods.stdout_lines | select('search', 'calico') | list | length > 0) else 'not_yet_applied' }}"

- name: Notify if Calico CNI manifest has been applied already
  debug:
    msg: |-
      Calico CNI manifest has been applied already.
  when: calico_cni_manifest == 'applied_already'

- name: Notify if Calico CNI manifest has not been applied yet
  debug:
    msg: |-
      Calico CNI manifest has not been applied yet. Proceeding to apply.
  when: calico_cni_manifest == 'not_yet_applied'

- name: Applying latest calico CNI  ( {{ calico_latest_version }} ) manifest from GitHub 
  command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ calico_latest_version }}/manifests/calico.yaml
  when: calico_cni_manifest == 'not_yet_applied'

############################### EOF ###################################
