- name: Create directory /home/{{ k8s_user }}/.kube
  file:
    path: "/home/{{ k8s_user }}/.kube"
    state: directory

- name: Copy /etc/kubernetes/admin.conf to /home/{{ k8s_user }}/.kube/config
  become: true
  copy:
    src: /etc/kubernetes/admin.conf
    remote_src: true
    dest: "/home/{{ k8s_user }}/.kube/config"
    owner: "{{ k8s_user }}"
    group: "{{ k8s_user }}"
    mode: "0600"

- name: Add kubectl completion to .bashrc of user {{ k8s_user }}
  lineinfile:
    path: "/home/{{ k8s_user }}/.bashrc"
    regexp: '^source <\(kubectl completion bash\)$'
    line: 'source <(kubectl completion bash)'
    state: present

##################################### EOF ######################################
