##Version : v2.1.7
- set_fact:
    var_k8s_ctrl_plane_node: "{{ ansible_host }}"
    var_k8s_user: "{{ ansible_user }}"

###Tasks for kubeadm config images pull
- name: Include tasks for kubeadm config images pull
  include_tasks: kubeadm_config_images_pull.yaml

###Tasks for kubeadm init
- name: Include tasks for kubeadm init
  include_tasks: kubeadm_init.yaml

###Tasks to create Kubernetes config for the k8s user
- name: Include tasks for creating Kubernetes config for user {{ var_k8s_user }}
  include_tasks: create_kube_config.yaml

###Task to check Kube API server's health
- name: Checking Kube API server's health (this might take some time).
  shell: curl -skL https://localhost:6443/healthz
  register: var_api_server_health_status
  until: var_api_server_health_status.stdout.find("ok") != -1
  retries: 100
  delay: 5

###Tasks to apply Calico CNI manifest
- name: Include tasks to apply Calico CNI manifest
  include_tasks: apply_calico_cni_manifest.yaml

###Tasks to check Ready status of control-plane node
- name: Wait for control-plane to get Ready
  shell: kubectl get nodes | grep -w " Ready "
  register: var_control_plane_ready_status
  retries: 100
  until: var_control_plane_ready_status.stdout.find("Ready") != -1
  delay: 5

- name: Get the status of control-plane node
  shell: kubectl get nodes | grep -i 'control-plane'
  register: var_nodes_status

- name: Notify the status of control-plane node
  debug:
    msg: |-
      {{ var_nodes_status.stdout_lines }}

###Tasks to create kubeadm token required for joining the worker nodes with the cluster
- name: Create kubeadm token required for joining the worker nodes with the cluster
  command: kubeadm token create --print-join-command
  register: var_kubeadm_join_command_register

- set_fact:
    var_kubeadm_join_command: "{{ var_kubeadm_join_command_register.stdout }}"

########################### EOF ##########################################
