##Version : v2.2.5
### Optional CSI SMB Driver for k8s cluster
- name: Check whether csi-smb-driver is already installed
  shell: |
    if kubectl get pods -A | grep -i 'csi-smb'
    then
      exit 0
    else
      exit 1
    fi
  register: var_csi_smb_install_status
  failed_when: false
  changed_when: false
  ignore_errors: true

- name: Notify if csi-smb-driver is already installed
  debug:
    msg: |-
      csi-smb-driver is already installed.
  when: var_csi_smb_install_status.rc == 0

- name: Get latest version information of k8s csi-smb-driver from github API
  delegate_to: local-ansible-control-host
  run_once: true
  uri:
    url: https://api.github.com/repos/kubernetes-csi/csi-driver-smb/releases/latest
    return_content: true
  register: var_csi_driver_smb_release
  changed_when: false
  when: var_csi_smb_install_status.rc == 1

- set_fact:
    var_csi_driver_smb_latest_version: "{{ var_csi_driver_smb_release.json.tag_name }}"
  when: var_csi_smb_install_status.rc == 1

- name: Notify the version to be installed of k8s csi-driver-smb
  debug:
    msg: |-
      Latest stable version to be installed of k8s csi-driver-smb is {{ var_csi_driver_smb_latest_version }}
  delegate_to: local-ansible-control-host
  run_once: true
  when: var_csi_smb_install_status.rc == 1

- name: Install CSI SMB drivers by remote from GitHub using kubectl
  shell: curl -skSL https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/{{ var_csi_driver_smb_latest_version }}/deploy/install-driver.sh | bash -s {{ var_csi_driver_smb_latest_version }} --
  register: var_csi_driver_smb_install_logs
  when: var_csi_smb_install_status.rc == 1

- name: Notify the results from CSI SMB drivers installation
  debug:
    msg: |-
      {{ var_csi_driver_smb_install_logs.stdout_lines }}
  when: var_csi_smb_install_status.rc == 1

- name: Get the creation status of csi-smb-driver pods
  shell: kubectl get pods -A | grep -i 'csi-smb'
  register: var_csi_driver_smb_pods_logs
  changed_when: false
  when: var_csi_smb_install_status.rc == 1

- name: Notify creation of CSI SMB driver pods
  debug:
    msg: |-
      {{ var_csi_driver_smb_pods_logs.stdout_lines }}
  when: var_csi_smb_install_status.rc == 1

- name: Capture the total number of CSI SMB driver pods
  shell: kubectl get pods -A --no-headers | grep -i 'csi-smb' | wc -l
  register: var_total_number_of_smb_pods
  changed_when: false
  when: var_csi_smb_install_status.rc == 1

- name: Wait for all the CSI SMB driver pods to come online (This might take some time)
  shell: kubectl get pods -A --no-headers | grep -i 'csi-smb' | grep 'Running' |  wc -l
  register: var_number_of_running_smb_pods
  until: var_number_of_running_smb_pods.stdout | int == var_total_number_of_smb_pods.stdout | int
  retries: 500
  delay: 5
  changed_when: false
  when: var_csi_smb_install_status.rc == 1

- name: Get the current status of csi-smb-driver pods
  shell: kubectl get pods -A | grep -i 'csi-smb'
  register: var_csi_driver_smb_pods_logs
  changed_when: false

- name: Status of csi-smb-driver pods if already installed
  debug:
    msg: |-
      {{ var_csi_driver_smb_pods_logs.stdout_lines }}
  when: var_csi_smb_install_status.rc == 0

- name: Successfully deployed CSI SMB driver pods for k8s cluster
  debug:
    msg: |-
      {{ var_csi_driver_smb_pods_logs.stdout_lines }}
  when: var_csi_smb_install_status.rc == 1

######################################## EOF #########################################
