##Version : v2.2.3
### Optional CSI SMB Driver for k8s cluster
- name: Get latest version information of k8s csi-smb-driver from github API
  delegate_to: local-ansible-control-host
  run_once: true
  uri:
    url: https://api.github.com/repos/kubernetes-csi/csi-driver-smb/releases/latest
    return_content: true
  register: var_csi_driver_smb_release

- set_fact:
    var_csi_driver_smb_latest_version: "{{ var_csi_driver_smb_release.json.tag_name }}"

- name: Notify the version to be installed of k8s csi-driver-smb
  debug:
    msg: |-
      Latest stable version to be installed of k8s csi-driver-smb is {{ var_csi_driver_smb_latest_version }}
  delegate_to: local-ansible-control-host
  run_once: true

- name: Install CSI SMB drivers by remote from GitHub using kubectl
  shell: curl -skSL https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/{{ var_csi_driver_smb_latest_version }}/deploy/install-driver.sh | bash -s {{ var_csi_driver_smb_latest_version }} --
  register: var_csi_driver_smb_install_logs

- name: Notify the results from CSI SMB drivers installation
  debug:
    msg: |-
      {{ var_csi_driver_smb_install_logs.stdout_lines }}

- name: Get the creation status of csi-smb-driver pods
  shell: kubectl get pods -A | grep -i 'csi-smb'
  register: var_csi_driver_smb_pods_logs

- name: Notify creation of CSI SMB driver pods
  debug:
    msg: |-
      {{ var_csi_driver_smb_pods_logs.stdout_lines }}

- name: Capture the total number of CSI SMB driver pods
  shell: kubectl get pods -A --no-headers | grep -i 'csi-smb' | wc -l
  register: var_total_number_of_smb_pods

- name: Wait for all the CSI SMB driver pods to come online (This might take some time)
  shell: kubectl get pods -A --no-headers | grep -i 'csi-smb' | grep 'Running' |  wc -l
  register: var_number_of_running_smb_pods
  until: var_number_of_running_smb_pods.stdout | int == var_total_number_of_smb_pods.stdout | int
  retries: 500
  delay: 5

- name: Get the current status of csi-smb-driver pods
  shell: kubectl get pods -A | grep -i 'csi-smb'
  register: var_csi_driver_smb_pods_logs

- name: Successfully deployed CSI SMB driver pods for k8s cluster
  debug:
    msg: |-
      {{ var_csi_driver_smb_pods_logs.stdout_lines }}

########################## EOF ############################
