##Version : v2.2.0
### Optional CSI SMB Driver for k8s cluster
- name: Get latest version information of k8s csi-smb-driver from github API
  delegate_to: local-ansible-control-host
  run_once: true
  uri:
    url: https://api.github.com/repos/kubernetes-csi/csi-driver-smb/releases/latest
    return_content: true
  register: var_csi_driver_smb_release

- set_fact:
    var_csi_driver_smb_latest_version: "{{ var_csi_driver_smb_release.json.tag_name }}"

- name: Notify the version to be installed of k8s csi-driver-smb
  debug:
    msg: |-
      Latest stable version to be installed of k8s csi-driver-smb is {{ var_csi_driver_smb_latest_version }}
  delegate_to: local-ansible-control-host
  run_once: true

- name: Install CSI SMB drivers by remote from GitHub using kubectl
  shell: curl -skSL https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/{{ var_csi_driver_smb_latest_version }}/deploy/install-driver.sh | bash -s {{ var_csi_driver_smb_latest_version }} --
  register: var_csi_driver_smb_install_logs

- name: Notify the results from CSI SMB drivers installation
  debug:
    msg: |-
      {{ var_csi_driver_smb_install_logs.stdout_lines }}

- name: completed, the csi-smb-driver pods are being deployed
  shell: kubectl get pods -A | grep -i csi-smb
  register: var_csi_driver_smb_pods_logs

- name: Notify that the CSI SMB drivers pod creations are started
  debug:
    msg: |-
      {{ var_csi_driver_smb_pods_logs.stdout_lines }}


########################## EOF ############################
