##Version : v2.1.5
### Role to check the k8s cluster Ready status
- name: worker nodes have already joinded the cluster, will be Ready in few minutes
  shell: kubectl get nodes
  register: var_nodes_status

- name: Notify current status of all cluster nodes
  debug:
    msg: |-
      {{ var_nodes_status.stdout_lines }}

- name: Wait for all worker nodes to get Ready
  shell: kubectl get nodes | grep -w "NotReady" | wc -l
  register: var_number_of_nodes_not_ready
  until: var_number_of_nodes_not_ready.stdout.find("0") != -1
  retries: 100
  delay: 5

- name: Add worker role label to the worker nodes
  shell: |
    for var_k8s_node in $(kubectl get nodes --no-headers | grep -i -v 'control-plane' | awk '{ print $1 }')
    do
        kubectl label node $var_k8s_node node-role.kubernetes.io/worker=true
    done
    exit

- name: Your kubernetes cluster is Ready!
  shell: kubectl get nodes
  register: var_nodes_status

- name: Manage this cluster from {{ var_k8s_ctrl_plane_node }} with user {{ var_k8s_user }}
  debug:
    msg: |-
      {{ var_nodes_status.stdout_lines }}

########################### EOF ###############################
