##Version : v2.1.2
### Role to check the k8s cluster Ready status
- name: worker nodes have already joinded the cluster, will be Ready in few minutes
  shell: kubectl get nodes
  register: var_nodes_status

- debug:
    msg: |-
      {{ var_nodes_status.stdout_lines }}

- name: Wait for all worker nodes to get Ready
  shell: kubectl get nodes | grep -w "NotReady" | wc -l
  register: var_number_of_nodes_not_ready
  until: var_number_of_nodes_not_ready.stdout.find("0") != -1
  retries: 100
  delay: 5

- name: Copy script that add role label to worker nodes 
  copy:
    src: "{{ var_label_worker_nodes_role_script }}"
    dest: "{{ var_label_worker_nodes_role_temp_script }}"
    mode: 0755

- name: Add worker role label to worker nodes
  command: sh "{{ var_label_worker_nodes_role_temp_script }}"

- name: k8s cluster nodes are Ready
  shell: kubectl get nodes
  register: var_nodes_status

- name: Mission accomplished! Now you can manage this k8s cluster from control plane node with user {{ var_k8s_user }}
  debug:
    msg: |-
      {{ var_nodes_status.stdout_lines }}

########################### EOF ###############################
