# roles/firewalld_setup/tasks/main.yaml

- name: Check if firewalld is active on RedHat-based or SUSE-based systems
  systemd:
    name: firewalld
    state: active
  register: firewalld_status
  changed_when: false
  failed_when: false  # Ensure this check does not fail the playbook
  when: ansible_os_family in ['RedHat', 'Suse']

- name: Notify if firewalld is not running on RedHat-based or SUSE-based systems
  debug:
    msg: "Firewalld is not running. Skipping firewall configuration."
  when: firewalld_status.status != "active" and ansible_os_family in ['RedHat', 'Suse']

- name: Include firewalld rules for Kubernetes on RedHat-based or SUSE-based systems
  include_tasks: apply_rules.yaml
  when: firewalld_status.status == "active" and ansible_os_family in ['RedHat', 'Suse']