##Version : v2.1.1
###Role to Register worker nodes with the k8s cluster with kubeadm join command
- name: Copy join command from  to the worker nodes
  copy:
    src: "{{ var_k8s_join_command_temp_script }}"
    dest: "{{ var_k8s_join_command_temp_script }}"
    mode: 0755

- name: Join the worker nodes with k8s cluster
  command: sudo sh "{{ var_k8s_join_command_temp_script }}"
