##Version : v2.1.5
###Role to Register worker nodes with the k8s cluster with kubeadm join command
- name: Check whether the worker node has joined the cluster already
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: var_check_k8s_kubelet_conf_file

- name: Notify if the worker node has joined the cluster already
  debug:
    msg: |-
      The worker node {{ ansible_host }} has joined the cluster already
  when: var_check_k8s_kubelet_conf_file.stat.exists

- command: "{{ hostvars[groups['k8s_cluster_ctrl_plane_node'][0]]['var_kubeadm_join_command'] }}"
  become: true
  register: var_worker_joined_output
  when: not var_check_k8s_kubelet_conf_file.stat.exists

- name: Notify output of join command result from worker node
  debug:
    msg: |
      {{ var_worker_joined_output.stdout_lines }}
  when: not var_check_k8s_kubelet_conf_file.stat.exists
